name: setup-prerequisites
on:
  workflow_call:
jobs:
  setup-prerequisites:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup prerequisites
        run: |
          apt-get update && apt-get install -y cppcheck clang cmake
          git config --global --add safe.directory /__w/m3mpt/m3mpt
          git submodule update --recursive --init  
